version: "3.8"

services:
  enshrouded:
    image: sknnr/enshrouded-dedicated-server:latest
    container_name: enshrouded-server
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${GAME_PORT}:${GAME_PORT}/udp"
      - "${QUERY_PORT}:${QUERY_PORT}/udp"

    volumes:
      - ./data:/home/steam/enshrouded/savegame
